version: '3.9'

services:

  poc.api.sqlserver-webapi:
    ports:
      - 5071:5071
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  poc.api.gateway-webapi:
    ports:
      - 5254:5254
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro  

  poc.api.mongodb-webapi:
    ports:
      - 5073:5073
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  
  poc.api.redis-webapi:
    ports:
      - 5074:5074
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

